import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import { useSession, signIn, signOut } from "next-auth/react"

const Homepage: NextPage = () => {
    const { data: session } = useSession()

    return (
        <div className={styles.container}>
            <Head>
                <title>Create Next App</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <nav className={styles.navbar}>
                <div className={styles.navbarLinks}>
                    <a href="#">Home</a>
                    {session && session.user ? (<a>Chapter</a>) : ""}
                    <a href="#">Contact</a>
                </div>
                <div className={styles.signup}>
                    {session && session.user ? (
                        <button onClick={() => signOut()}>Sign out</button>
                    ) : (
                        <button onClick={() => signIn()}>Sign in</button>
                    )}
                </div>
            </nav>
            <main className={styles.main}>
                <div>
                    {session && session.user ? (
                        <div><p>Hey {session.user.name} We are happy you logged in with {session.user.email}</p></div>
                    ) : (
                        <p>You need to sign in to Start Reading Bhagwat Gita</p>
                    )}
                </div>
            </main>
        </div>
    )
}

export default Homepage;