import type { NextPage } from 'next';
import Head from 'next/head';
import Image from 'next/image';
import { useSession, signIn, signOut } from "next-auth/react";
import ChapterSelector from '@/components/chapterselector';
import styles from '../styles/Home.module.css'

const Homepage: NextPage = () => {
    const { data: session } = useSession();

    return (
        <div className="min-h-screen bg-gray-100">
            <Head>
                <title>Create Next App</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <nav className="bg-blue-500 p-4">
                <div className="flex justify-between items-center">
                    <a href="#" className="text-white font-bold text-xl">Home</a>
                    {session && session.user ? (
                        <div className="relative group">
                            {/* <select className="text-black font-semibold bg-white border border-gray-400 rounded-md px-3 py-2">
                                <option value="" disabled hidden>Select a Chapter</option>
                                {Array.from({ length: 18 }, (_, i) => (
                                    <option key={i} value={`chapter${i + 1}`}>Chapter {i + 1}</option>
                                ))}
                            </select> */}
                            <ChapterSelector />

                            <span className="absolute inset-y-0 right-0 flex items-center pr-2 pointer-events-none">
                                <svg className="h-5 w-5 text-white transform group-hover:rotate-180 transition-transform" fill="none" stroke="currentColor" viewBox="0 0 24 24" xmlns="http://www.w3.org/2000/svg">
                                    <path strokeLinecap="round" strokeLinejoin="round" strokeWidth="2" d="M19 9l-7 7-7-7"></path>
                                </svg>
                            </span>
                        </div>
                    ) : ""}
                    <div className={styles.signup}>
                        {session && session.user ? (
                            <button className="text-white font-bold text-xl" onClick={() => signOut()}>Sign out</button>
                        ) : (
                            <button className="text-white font-bold text-xl" onClick={() => signIn()}>Sign in</button>
                        )}
                    </div>
                </div>
            </nav>

            <main className="max-w-screen-lg mx-auto py-8">
                <div className="text-center">
                    {session && session.user ? (
                        <div>
                            <p className="text-2xl font-semibold text-blue-500">Hey {session.user.name}, happy you logged in with {session.user.email}

                                Get Ready to read the ultimate bhagwat gita
                            </p>
                        </div>
                    ) : (
                        <p className="text-xl font-semibold text-blue-500">You need to sign in to start reading Bhagwat Gita</p>
                    )}
                </div>
            </main>
        </div>
    );
};

export default Homepage;
